DEBUG = True

PORT = 8000

DB_HOST = '10.143.143.88'
DB_PORT = 3306
DB_NAME = 'backend'
DB_USER = 'root'
DB_PASS = '0OMhLmapbaU2HKgq'

REDIS_HOST = '10.143.143.88'
REDIS_PORT = 6379
REDIS_PASS = 'S0LZ7eO5DGiS31nT'
REDIS_DB = 0
REDIS_CHANNEL = "SERVICE_CHANNEL"


ACTION_DIR_NAME = ("action", )

STATIC_DIR_NAME = "static"

TEMPLATE_DIR_NAME = "template"

COOKIE_SECRET = "Cookie_Secret"

API_VERSION = "/api"

